version: '3.7'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: app
    restart: always
    container_name: auta_frontend
    environment:
      - DB_HOST=mariadb
    ports:
      - 5002:5000
    depends_on:
      - backend
    secrets:
      - db_name
      - db_user
      - db_password
    volumes:
      - ./frontend:/app # for live reloading code
    networks:
      - zcekni_auto_internal
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: app
    container_name: auta_backend
    volumes:
      - ./backend:/app
    ports:
      -  5001:5001
    depends_on:
      - mariadb
    networks:
      - zcekni_auto_internal
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306 # for debugging connection from host
    container_name: auta_sql_database
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_name
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_name
      - db_user
      - db_password
    networks:
      - zcekni_auto_internal
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379 # for debugging connection from host
    networks:
      - zcekni_auto_internal
    secrets:
      - redis_password # TODO: verify this actually gets used
    configs:
      - source: configs/redis.conf
        target: /usr/local/etc/redis/redis.conf

secrets:
  db_root_password:
    file: ./secrets/db_root_password
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  redis_password:
    file: ./secrets/redis_password
networks:
  zcekni_auto_internal:
    driver: bridge
volumes:
  db-data:
    driver: local